# Generated by Django 5.0.4 on 2024-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
