# Generated by Django 5.0.4 on 2024-04-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
